~say hi to==mp4:hello.mp4
hello==mp4:hello.mp4
photos==launch:photos
emotes==launch:beemotes
about box==launch:about
~play video games==launch:videogames
how many fingers am i holding up==mp4:beep1.mp4
beep==mp4:beep1.mp4
beat==mp4:beep1.mp4
beef==mp4:beep1.mp4
~you're funny==mp4:hahaha.mp4
~make me laugh==mp4:hahaha.mp4
~wave your arms==system:/home/pi/bmos/servos/waveboth
~wave your arm==system:/home/pi/bmos/servos/waveright
~birthday==mp4:birsday.mp4
defend me==system:/home/pi/bmos/scripts/choparm.sh